version: "3"
services:
  strips:
    build:
      context: .
      dockerfile: "src/docker/Dockerfile"
      args:
        JAR_FILE_NAME: "strips-0.0.1-SNAPSHOT.jar"
        SRC_DIR: "."
    ports:
      - "8080:8080"
